In [18]:
import requests
from bs4 import BeautifulSoup

url = 'http://www.showmeboone.com/sheriff/JailResidents/JailResidents.asp'
response = requests.get(url)
html = response.content

soup = BeautifulSoup(html)
table = soup.find('tbody', attrs={'class': 'stripe'})
print(table.prettify())
for row in table.findAll('tr'):
    list_of_cells = []
    for cell in row.findAll('td'):
        text = cell.text.replace('&nbsp;', '')
        list_of_cells.append(text)
        print(list_of_cells)
    

    
## print(soup.prettify())

<tbody class="stripe" id="mrc_main_table">
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   ACTON
  </td>
  <td class="one td_left" data-th="First Name">
   ANTHONY
  </td>
  <td class="one td_left" data-th="Middle Name">
   SEAN
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   B
  </td>
  <td class="one td_right" data-th="Age">
   26
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=66619&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   AKERS
  </td>
  <td class="two td_left" data-th="First Name">
   SYDNEY
  </td>
  <td class="two td_left" data-th="Middle Name">
   RAE
  </td>
  <td class="two td_left" data-th="Sex">
   F
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   21
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=76028&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   AL-AQUIL
  </td>
  <td class="one td_left" data-th="First Name">
   MOHAMMED
  </td>
  <td class="one td_left" data-th="Middle Name">
   NASSER
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   U
  </td>
  <td class="one td_right" data-th="Age">
   27
  </td>
  <td class="one td_left" data-th="City">
   ST. LOUIS
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=81641&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   ALLEN
  </td>
  <td class="two td_left" data-th="First Name">
   JEREMY
  </td>
  <td class="two td_left" data-th="Middle Name">
   ADRIAN
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   40
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=81762&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   ARMSTRONG
  </td>
  <td class="one td_left" data-th="First Name">
   ANTIONE
  </td>
  <td class="one td_left" data-th="Middle Name">
   LAMONT
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   B
  </td>
  <td class="one td_right" data-th="Age">
   18
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=79483&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   ASHFORD
  </td>
  <td class="two td_left" data-th="First Name">
   NEELEY
  </td>
  <td class="two td_left" data-th="Middle Name">
   DIANA
  </td>
  <td class="two td_left" data-th="Sex">
   F
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   41
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=47913&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   AULL
  </td>
  <td class="one td_left" data-th="First Name">
   JONATHAN
  </td>
  <td class="one td_left" data-th="Middle Name">
   MORGAN
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   37
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=29434&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BAKER
  </td>
  <td class="two td_left" data-th="First Name">
   CHAD
  </td>
  <td class="two td_left" data-th="Middle Name">
   EDWARD
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   30
  </td>
  <td class="two td_left" data-th="City">
   THOMPSON
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=57253&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BAKER
  </td>
  <td class="one td_left" data-th="First Name">
   MEGUN
  </td>
  <td class="one td_left" data-th="Middle Name">
   ANN
  </td>
  <td class="one td_left" data-th="Sex">
   F
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   31
  </td>
  <td class="one td_left" data-th="City">
   PRAIRIE HOME
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=47794&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BANKS
  </td>
  <td class="two td_left" data-th="First Name">
   HAROLD
  </td>
  <td class="two td_left" data-th="Middle Name">
   JOSEPH
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   B
  </td>
  <td class="two td_right" data-th="Age">
   17
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=81801&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BARNES
  </td>
  <td class="one td_left" data-th="First Name">
   BRENDA
  </td>
  <td class="one td_left" data-th="Middle Name">
   SUE
  </td>
  <td class="one td_left" data-th="Sex">
   F
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   40
  </td>
  <td class="one td_left" data-th="City">
   ST. LOUIS
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=29813&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BARNETTE-KRUGER
  </td>
  <td class="two td_left" data-th="First Name">
   ANDREW
  </td>
  <td class="two td_left" data-th="Middle Name">
   LAWRANCE
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   B
  </td>
  <td class="two td_right" data-th="Age">
   25
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=62060&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BARNEY
  </td>
  <td class="one td_left" data-th="First Name">
   FELSON
  </td>
  <td class="one td_left" data-th="Middle Name">
   DEVONE
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   B
  </td>
  <td class="one td_right" data-th="Age">
   41
  </td>
  <td class="one td_left" data-th="City">
   SPRINGFIELD
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=4285&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BARNEY
  </td>
  <td class="two td_left" data-th="First Name">
   FREDERICK
  </td>
  <td class="two td_left" data-th="Middle Name">
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   B
  </td>
  <td class="two td_right" data-th="Age">
   34
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=40509&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BARNEY
  </td>
  <td class="one td_left" data-th="First Name">
   LARCELL
  </td>
  <td class="one td_left" data-th="Middle Name">
   CHRISTOPHER
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   B
  </td>
  <td class="one td_right" data-th="Age">
   44
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=14686&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BARTON
  </td>
  <td class="two td_left" data-th="First Name">
   KRISTE
  </td>
  <td class="two td_left" data-th="Middle Name">
   MARIE
  </td>
  <td class="two td_left" data-th="Sex">
   F
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   33
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=39416&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BENEDETTI
  </td>
  <td class="one td_left" data-th="First Name">
   FRANK
  </td>
  <td class="one td_left" data-th="Middle Name">
   DOMINICK
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   29
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=79913&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BLACK
  </td>
  <td class="two td_left" data-th="First Name">
   ISAIAH
  </td>
  <td class="two td_left" data-th="Middle Name">
   JAYSON
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   21
  </td>
  <td class="two td_left" data-th="City">
   STURGEON
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=73501&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BLEVINS
  </td>
  <td class="one td_left" data-th="First Name">
   JESSE
  </td>
  <td class="one td_left" data-th="Middle Name">
   RAY
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   29
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=68185&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BLUMHORST
  </td>
  <td class="two td_left" data-th="First Name">
   DWIGHT
  </td>
  <td class="two td_left" data-th="Middle Name">
   THOMAS
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   W
  </td>
  <td class="two td_right" data-th="Age">
   34
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=75833&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BOWDEN
  </td>
  <td class="one td_left" data-th="First Name">
   BRANDON
  </td>
  <td class="one td_left" data-th="Middle Name">
   LEE
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   32
  </td>
  <td class="one td_left" data-th="City">
   ASHLAND
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=81584&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BOYD
  </td>
  <td class="two td_left" data-th="First Name">
   LEE
  </td>
  <td class="two td_left" data-th="Middle Name">
   DEMAREO
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   B
  </td>
  <td class="two td_right" data-th="Age">
   32
  </td>
  <td class="two td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=46658&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="odd">
  <td class="one td_left" data-th="Last Name">
   BRAWLEY
  </td>
  <td class="one td_left" data-th="First Name">
   DONALD
  </td>
  <td class="one td_left" data-th="Middle Name">
   GLEN
  </td>
  <td class="one td_left" data-th="Sex">
   M
  </td>
  <td class="one td_left" data-th="Race">
   W
  </td>
  <td class="one td_right" data-th="Age">
   42
  </td>
  <td class="one td_left" data-th="City">
   COLUMBIA
  </td>
  <td class="one td_left" data-th="State">
   MO
  </td>
  <td class="one td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=9240&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">
    <i class="fa fa-large fa-fw fa-list-alt">
    </i>
    Details
   </a>
  </td>
 </tr>
 <!-- -->
 <tr class="even">
  <td class="two td_left" data-th="Last Name">
   BROWN
  </td>
  <td class="two td_left" data-th="First Name">
   BARRY
  </td>
  <td class="two td_left" data-th="Middle Name">
   RONELL
  </td>
  <td class="two td_left" data-th="Sex">
   M
  </td>
  <td class="two td_left" data-th="Race">
   B
  </td>
  <td class="two td_right" data-th="Age">
   31
  </td>
  <td class="two td_left" data-th="City">
   FLORISSANT
  </td>
  <td class="two td_left" data-th="State">
   MO
  </td>
  <td class="two td_left" data-th="">
   <a class="_lookup btn btn-primary" height="600" href="SH01_MP.I00500s?PERKEP=80297&amp;hover_redir=&amp;height=600&amp;width=950" linkedtype="I" mrc="returndata" target="_lookup" width="860">